// Generated by gencpp from file wheelchair_bed_msgs/dht.msg
// DO NOT EDIT!


#ifndef WHEELCHAIR_BED_MSGS_MESSAGE_DHT_H
#define WHEELCHAIR_BED_MSGS_MESSAGE_DHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheelchair_bed_msgs
{
template <class ContainerAllocator>
struct dht_
{
  typedef dht_<ContainerAllocator> Type;

  dht_()
    : temp(0.0)
    , humi(0.0)  {
    }
  dht_(const ContainerAllocator& _alloc)
    : temp(0.0)
    , humi(0.0)  {
  (void)_alloc;
    }



   typedef float _temp_type;
  _temp_type temp;

   typedef float _humi_type;
  _humi_type humi;





  typedef boost::shared_ptr< ::wheelchair_bed_msgs::dht_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheelchair_bed_msgs::dht_<ContainerAllocator> const> ConstPtr;

}; // struct dht_

typedef ::wheelchair_bed_msgs::dht_<std::allocator<void> > dht;

typedef boost::shared_ptr< ::wheelchair_bed_msgs::dht > dhtPtr;
typedef boost::shared_ptr< ::wheelchair_bed_msgs::dht const> dhtConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheelchair_bed_msgs::dht_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheelchair_bed_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'wheelchair_bed_msgs': ['/home/aibot/wheelchair_bed/src/wheelchair_bed_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_bed_msgs::dht_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheelchair_bed_msgs::dht_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_bed_msgs::dht_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "589c35b88a26ab074d5f9b9dc60c010e";
  }

  static const char* value(const ::wheelchair_bed_msgs::dht_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x589c35b88a26ab07ULL;
  static const uint64_t static_value2 = 0x4d5f9b9dc60c010eULL;
};

template<class ContainerAllocator>
struct DataType< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheelchair_bed_msgs/dht";
  }

  static const char* value(const ::wheelchair_bed_msgs::dht_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temp\n\
float32 humi\n\
";
  }

  static const char* value(const ::wheelchair_bed_msgs::dht_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
      stream.next(m.humi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dht_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheelchair_bed_msgs::dht_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheelchair_bed_msgs::dht_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
    s << indent << "humi: ";
    Printer<float>::stream(s, indent + "  ", v.humi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELCHAIR_BED_MSGS_MESSAGE_DHT_H
